# Generated by Django 5.0.6 on 2024-07-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'SubjectStatus',
                'verbose_name_plural': 'SubjectStatuses',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Subject name')),
                ('description', models.TextField(verbose_name='Subject description')),
                ('img', models.ImageField(upload_to='media')),
                ('subjectstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.subjectstatus')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
