# Generated by Django 5.0.6 on 2024-07-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectstatus',
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name='subject',
            name='link',
            field=models.CharField(default=1, max_length=100, verbose_name='link name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubjectStatus',
        ),
    ]
