# Generated by Django 5.0.6 on 2024-07-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_subject_subjectstatus_subject_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/subjects'),
        ),
    ]
