# Generated by Django 5.0.6 on 2024-07-09 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subject_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=models.FileField(default=1, upload_to='media/subjects', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
            preserve_default=False,
        ),
    ]
