# Generated by Django 5.0.6 on 2024-09-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_region_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='main.region'),
            preserve_default=False,
        ),
    ]
