# Generated by Django 5.0.6 on 2024-09-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_school_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='region',
        ),
    ]
