# Generated by Django 5.0.6 on 2024-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
