# Generated by Django 5.0.6 on 2024-11-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userprofile_region_alter_userprofile_school_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
